- docker/jenkins-slave/Dockerfile
Reverts Kiali-QE/kiali-qe-python#39
> Revert "virtualenv added in docker image"

- kiali_qe/components/__init__.py
- kiali_qe/components/enums.py
- kiali_qe/entities/istio_config.py
- kiali_qe/fixtures/rest_client.py
- kiali_qe/rest/kiali_api.py
- kiali_qe/rest/openshift_api.py
- kiali_qe/tests/__init__.py
- kiali_qe/tests/conftest.py
- kiali_qe/tests/test_istio_config_page.py
- kiali_qe/tests/test_services_page.py
- requirements.txt
* Returned back OpenShift client and tests
* Update Istio Config page changes
> Returned back OpenShift client and updated UI changes

- kiali_qe/components/__init__.py
- kiali_qe/pages/__init__.py
* log-in page added
* hard-coded credentials
* Another PR will be created to fetch credentials from yaml file
> login page support, added hard-coded credentials

- kiali_qe/components/__init__.py
- kiali_qe/tests/__init__.py
* Fixes unstable issue on services page(when using a filter)
* Removed `\n` from username and password entry
> fix unstable filter page and login page issue

- kiali_qe/components/__init__.py
- kiali_qe/components/enums.py
* New option added in graph page filter, `Legend`
> fix a failure in graph page

- kiali_qe/tests/__init__.py
- kiali_qe/tests/test_istio_config_page.py
- kiali_qe/tests/test_services_page.py
* Changed `assert_all_items` as usable by other tests
* Added little document for `assert_all_items`
* changes in existing test to adopt with `assert_all_items` change
> Allow user to utilize 'assert_all_items'

- kiali_qe/components/__init__.py
- kiali_qe/tests/test_applications_page.py
- kiali_qe/tests/test_services_page.py
- kiali_qe/tests/test_workloads_page.py
Also use only istio-system namespace which is sufficient for these
tests. It will also reduce execution time.
> Wait for page to be loaded when using pagination feature.

- kiali_qe/components/__init__.py
- kiali_qe/entities/workload.py
- kiali_qe/tests/__init__.py
Fixed service details DR tabs parsing
> Enabled Metrics tabs tests

- kiali_qe/components/enums.py
- kiali_qe/rest/kiali_api.py
- kiali_qe/rest/openshift_api.py
- kiali_qe/tests/__init__.py
Reverts Kiali-QE/kiali-qe-python#132
> Revert "Istio Config Details: OC call"

- kiali_qe/components/enums.py
- kiali_qe/tests/test_navbar.py
Added check if about has Maistra or Istio to display the versions
> SWSQE-575 - Support for Maistra version

- conf/env.yaml
- kiali_qe/components/enums.py
- kiali_qe/fixtures/rest_client.py
- kiali_qe/rest/kiali_api.py
- kiali_qe/rest/openshift_api.py
- kiali_qe/tests/__init__.py
Added new config to activate that.
> Temporary solution for OC Client switching all calls to Kiali Rest API.

- kiali_qe/components/__init__.py
Maybe we will want to ask devs to update the el class to something more
meaningfull
> Quick fix for Success icon

- kiali_qe/rest/kiali_api.py
https://github.com/kiali/kiali/pull/1870 and https://github.com/kiali/kiali/pull/1888 are cleaning empty values from JSON so we need to update our tests.
> Check that trafficPolicy exists before accessing

- kiali_qe/components/__init__.py
- kiali_qe/tests/__init__.py
> More logs for failures.

- kiali_qe/components/enums.py
Reverts Kiali-QE/kiali-qe-python#238
> Revert "Fixed changed enum values"

- data/resources/istio_objects/validation/port_name_suffix_missing.yaml
- kiali_qe/components/__init__.py
- kiali_qe/components/enums.py
- kiali_qe/entities/applications.py
- kiali_qe/entities/service.py
- kiali_qe/entities/workload.py
- kiali_qe/rest/kiali_api.py
- kiali_qe/rest/openshift_api.py
- kiali_qe/tests/__init__.py
- kiali_qe/tests/test_applications_page.py
- kiali_qe/tests/test_services_page.py
- kiali_qe/tests/test_workloads_page.py
- kiali_qe/utils/__init__.py
PF4 related changes, more fixes. Added more tests for label filters in Apps, Workloads and Services.
> Fixed failing tests based on latest UI changes.

- kiali_qe/components/__init__.py
- kiali_qe/components/enums.py
- kiali_qe/rest/kiali_api.py
- kiali_qe/rest/openshift_api.py
Depends on https://github.com/kiali/kiali/pull/2881
> Fixed failing tests by changing Kiali API and OC API calls

- kiali_qe/tests/test_overview_page.py
Added a test for filter by labels on overview page.
> SWSQE-1202 - Update overview filter test

- kiali_qe/components/enums.py
Upstream Kiali has updated the values.
> Fixing the values in enums.py:UI

- kiali_qe/components/enums.py
- kiali_qe/tests/test_overview_page.py
Added new Health test cases for the Overview page.
> Added_OverviewHealth_enum_values

- kiali_qe/components/enums.py
- kiali_qe/tests/test_workloads_page.py
Added tests for workload health filter
> Workload healthfilter

- kiali_qe/tests/test_istio_config_page.py
Added filter tests for 'Istio Type' and 'Config'
> Add config filter tests

- kiali_qe/components/error_codes.py
- kiali_qe/tests/test_istio_config_validation.py
- kiali_qe/tests/test_istio_objects_crud.py
> KIA0203 - If host not found, kiali will never find workloads matching labels

- kiali_qe/pages/__init__.py
Graph type format has been changed, update the Graph_type_format
this would be tested against -> test_graph_page.py/test_type
> UI: Graph Type

- kiali_qe/components/enums.py
- kiali_qe/tests/test_graph_page.py
updated the test_graph_page.py and enums values for Graph
> UI: Graph Display Settings

- kiali_qe/rest/openshift_api.py
fixes testcases  in test_istio_config_mtls.py
> fixing napespace in configmap

- kiali_qe/tests/test_applications_page.py
> Update Application filters

- kiali_qe/tests/__init__.py
REST result returns still invalid values, disabling asserts by commenting out
> commenting out more rest logic

- kiali_qe/tests/__init__.py
- kiali_qe/tests/test_applications_page.py
fixing tests:
_test_filter_applications_istio_sidecar_not_present_
_test_filter_applications_istio_sidecar_present_
> changing assert_all_items to apply_filters

- kiali_qe/rest/kiali_api.py
- requirements.txt
> fixing tests in overview page

- kiali_qe/tests/test_breadcrumb.py
> breadcrumb fixing

- kiali_qe/rest/kiali_api.py
fixing these test cases:
test_tls_mutual test case fixing
test_service_details_random
test_tcp_routing_single
> fixing _routing_wizard

- kiali_qe/tests/test_istio_config_validation.py
Verified these test_cases locally and modified the changes.
> Fix_Istio_validations

- kiali_qe/components/enums.py
- kiali_qe/tests/test_graph_page.py
> fix_graph_display_rate

- kiali_qe/components/enums.py
- kiali_qe/components/error_codes.py
- kiali_qe/tests/test_breadcrumb.py
- kiali_qe/tests/test_istio_objects_crud.py
kiali_qe.tests.test_breadcrumb.test_config_breadcrumb_menu
kiali_qe.tests.test_breadcrumb.test_config_breadcrumb_namespace
kiali_qe.tests.test_breadcrumb.test_config_breadcrumb_object
kiali_qe.tests.test_istio_objects_crud.test_auth_policy
kiali_qe.tests.test_services_page.test_filter_options
Fixed these test_cases
> fix_lastest_failures

- kiali_qe/components/error_codes.py
- kiali_qe/tests/test_filters.py
- kiali_qe/tests/test_istio_objects_crud.py
Fixed these two test cases
kiali_qe.tests.test_istio_objects_crud.test_virtual_service_subset_warning
kiali_qe.tests.test_filters.test_config_filters_kept
> fix_filters_and_Istio_crub

- kiali_qe/tests/test_services_page.py
fixing testcase
test_istio_objects_crud.test_requestauth_create
modified condition in filter
> fixtest_istio_objects_crud.test_requestauth_create

- kiali_qe/tests/__init__.py
- kiali_qe/tests/test_istio_config_validation.py
kiali_qe.tests.test_istio_config_validation.test_vs_duplicate_gateway
kiali_qe.tests.test_istio_objects_crud.test_authpolicy_rules_allow_create 
kiali_qe.tests.test_istio_objects_crud.test_authpolicy_allow_all_create
Fixed these 3 test cases
> Update test vs duplicate gateway

- kiali_qe/tests/test_graph_page.py
kiali_qe.tests.test_graph_page.test_type   --> fixed this test case
> fix_graph_test_type

- kiali_qe/entities/service.py
- kiali_qe/tests/__init__.py
test_services_page
- test_service_details_random
- test_service_details_kiali
> regression fixes in test_services_page

- kiali_qe/tests/test_istio_config_mtls.py
- kiali_qe/tests/test_istio_objects_crud.py
skipping flaky tests because of interop pipeline
> added annotation for skipping flaky tests

- kiali_qe/tests/__init__.py
fixed test test_service_graph_overview
> fixed namespace in side_panel.get_namespace

- conf/env.yaml
use istio-install-istio-system for downstream and istio for upstream
> fixed configMapName default value

- kiali_qe/tests/test_breadcrumb.py
- kiali_qe/tests/test_graph_page.py
- kiali_qe/tests/test_overview_page.py
disabled more test for interop pipeline
> Kiali 2.1 interop

- kiali_qe/components/__init__.py
- kiali_qe/tests/test_routing_wizard.py
test_matching_routing_multi
test_routing_keep_advanced_settings
> fixing tests 

- conf/env.yaml
- kiali_qe/tests/__init__.py
fixing test_istio_config_page.test_all_configs
and possibly others using 3-way check
> Kiali 2.1 downstream fix

- kiali_qe/components/__init__.py
- kiali_qe/tests/__init__.py
kiali_qe.tests.test_overview_page.test_overview_auto_injection
kiali_qe.tests.test_overview_page.test_overview_traffic_policies
> Fix_Overview_Failure_testcases

- kiali_qe/tests/test_breadcrumb.py
Reverts Kiali-QE/kiali-qe-python#510
> Revert "Update breadcrumb failures"

- kiali_qe/tests/test_istio_objects_crud.py
test_peerauth_create_disabled
Updated and fixed this test case
> Updated Peerauth create disabled

- kiali_qe/rest/kiali_api.py
> Validation_fix_routing

- kiali_qe/components/enums.py
- kiali_qe/tests/test_dr_hosts.py
Host Pr, Istio config page side panel updated with Overview, References and Help
before side panel update
After side panel update
> Istio link update

- conf/env.yaml
- kiali_qe/components/browser.py
- kiali_qe/components/enums.py
- kiali_qe/fixtures/browser.py
- kiali_qe/fixtures/rest_client.py
- kiali_qe/tests/test_navbar.py
There is only one component now instead of kiali-core and kiali-ui
> OSSM-1410: kiali core and kiali ui were merged into one repo

- kiali_qe/components/__init__.py
- kiali_qe/components/enums.py
- kiali_qe/pages/__init__.py
- kiali_qe/tests/__init__.py
> fixing_pf_changes

- kiali_qe/tests/test_istio_config_validation.py
These test cases migrated to Cypress.
> disable_istio_validation_cypress
